//
//  main.go
//  tools/core
//
//  Created by [Camilo Castro (@clsource)](https://ninjas.cl) on 2026-09-17
//  Made with love in Chile.
//
//  Copyright (c) Jasonelle.com
//
//  This file is part of Jasonelle Project <https://jasonelle.com>.
//  Jasonelle Project is dual licensed. You can choose between AGPLv3 or MPLv2.
//  MPLv2 is only valid if the software has a unique Jasonelle Key which was purchased in official channels at https://jasonelle.com.
//
//  == AGPLv3
//  Jasonelle is free software: you can redistribute it and/or modify it under the terms of the Affero GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//  Jasonelle is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the Affero GNU General Public License for more details.
//  You should have received a copy of the Affero GNU General Public License along with Jasonelle. If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
//
//  == MPLv2 (Only valid if purchased a Jasonelle Key)
//  This Source Code Form is subject to the terms
//  of the Mozilla Public License, v. 2.0.
//  If a copy of the MPL was not distributed
//  with this file, You can obtain one at
//
//  <https://mozilla.org/MPL/2.0/>.
//

package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fatal(err)
	}
}

func run(args []string) error {
	fs := flag.NewFlagSet("core", flag.ContinueOnError)
	xcodeSrc := fs.String("xcode", "sources/xcode", "path to the Xcode core sources")
	androidSrc := fs.String("android", "sources/android", "path to the Android core sources")
	xcodeLib := fs.String("xcode-lib", "lib/xcode/sources", "path to the Xcode override sources")
	androidLib := fs.String("android-lib", "lib/android/sources", "path to the Android override sources")
	only := fs.String("only", "", "only assemble this platform (xcode or android)")
	if err := fs.Parse(args); err != nil {
		return err
	}

	if *only != "" && *only != "xcode" && *only != "android" {
		return fmt.Errorf("--only must be xcode or android, got %q", *only)
	}

	if *only == "" || *only == "xcode" {
		if err := assemble(*xcodeSrc, *xcodeLib, filepath.Join("build", "xcode", "sources")); err != nil {
			return fmt.Errorf("xcode: %w", err)
		}
	}
	if *only == "" || *only == "android" {
		if err := assemble(*androidSrc, *androidLib, filepath.Join("build", "android", "sources")); err != nil {
			return fmt.Errorf("android: %w", err)
		}
	}
	return nil
}

// assemble copies the core sources into dest, overlaying the lib overrides.
// Precedence for a given relative path is: lib override wins, then an already
// existing dest file (e.g. Plugins.swift generated by the plugins tool), then
// the stock core file. Files under a top-level JLPlugin* directory belong to
// the plugins tool and are skipped. Nothing is ever deleted.
func assemble(src, lib, dest string) error {
	if err := copyCore(src, dest); err != nil {
		return err
	}
	return copyLib(lib, dest)
}

// copyCore copies src into dest, skipping top-level JLPlugin* directories and
// files that already exist in dest.
func copyCore(src, dest string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		top := strings.SplitN(rel, string(filepath.Separator), 2)[0]
		if strings.HasPrefix(top, "JLPlugin") {
			if info.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if info.IsDir() {
			return nil
		}
		target := filepath.Join(dest, rel)
		if _, err := os.Stat(target); err == nil {
			return nil
		}
		return copyFile(path, target)
	})
}

// copyLib copies every file in lib into dest, replacing any existing file.
func copyLib(lib, dest string) error {
	if _, err := os.Stat(lib); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	return filepath.Walk(lib, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(lib, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		if info.IsDir() {
			return nil
		}
		return copyFile(path, filepath.Join(dest, rel))
	})
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
