//
//  main_test.go
//  tools/core
//
//  Created by [Camilo Castro (@clsource)](https://ninjas.cl) on 2026-09-17
//  Made with love in Chile.
//
//  Copyright (c) Jasonelle.com
//
//  This file is part of Jasonelle Project <https://jasonelle.com>.
//  Jasonelle Project is dual licensed. You can choose between AGPLv3 or MPLv2.
//  MPLv2 is only valid if the software has a unique Jasonelle Key which was purchased in official channels at https://jasonelle.com.
//
//  == AGPLv3
//  Jasonelle is free software: you can redistribute it and/or modify it under the terms of the Affero GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//  Jasonelle is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the Affero GNU General Public License for more details.
//  You should have received a copy of the Affero GNU General Public License along with Jasonelle. If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
//
//  == MPLv2 (Only valid if purchased a Jasonelle Key)
//  This Source Code Form is subject to the terms
//  of the Mozilla Public License, v. 2.0.
//  If a copy of the MPL was not distributed
//  with this file, You can obtain one at
//
//  <https://mozilla.org/MPL/2.0/>.
//

package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestAssembleCore(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "src")
	lib := filepath.Join(dir, "lib")
	dest := filepath.Join(dir, "dest")

	mkfile(t, src, "Application/Application/Plugins.swift", "stock plugins")
	mkfile(t, src, "JLKernel/Kernel.swift", "kernel")
	mkfile(t, src, "README.md", "readme")
	// Plugin directory owned by the plugins tool: must be skipped
	mkfile(t, src, "JLPluginHello/Plugin.swift", "stock plugin")

	// The plugins tool already generated Plugins.swift in dest, and the user
	// provides a lib override for it.
	mkfile(t, dest, "Application/Application/Plugins.swift", "generated by plugins tool")
	mkfile(t, lib, "Application/Application/Plugins.swift", "lib override")
	// Brand-new lib file with no stock counterpart.
	mkfile(t, lib, "Custom/Extra.swift", "extra")

	if err := assemble(src, lib, dest); err != nil {
		t.Fatal(err)
	}

	assertFile(t, dest, "Application/Application/Plugins.swift", "lib override")
	assertFile(t, dest, "JLKernel/Kernel.swift", "kernel")
	assertFile(t, dest, "README.md", "readme")
	assertFile(t, dest, "Custom/Extra.swift", "extra")
	if _, err := os.Stat(filepath.Join(dest, "JLPluginHello")); err == nil {
		t.Errorf("JLPluginHello must not be copied by core")
	}
}

func TestAssembleKeepsExisting(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "src")
	lib := filepath.Join(dir, "lib")
	dest := filepath.Join(dir, "dest")

	mkfile(t, src, "Application/Application/Plugins.swift", "stock plugins")
	mkfile(t, dest, "Application/Application/Plugins.swift", "generated by plugins tool")

	if err := assemble(src, lib, dest); err != nil {
		t.Fatal(err)
	}

	assertFile(t, dest, "Application/Application/Plugins.swift", "generated by plugins tool")
}

func TestAssemblePreservesUnrelated(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "src")
	lib := filepath.Join(dir, "lib")
	dest := filepath.Join(dir, "dest")

	mkfile(t, src, "JLKernel/Kernel.swift", "kernel")
	// Files placed in dest by other tools must survive.
	mkfile(t, dest, "config/config.jsonc", "cfg")
	mkfile(t, dest, "scripts/webview.js", "js")

	if err := assemble(src, lib, dest); err != nil {
		t.Fatal(err)
	}

	assertFile(t, dest, "config/config.jsonc", "cfg")
	assertFile(t, dest, "scripts/webview.js", "js")
	assertFile(t, dest, "JLKernel/Kernel.swift", "kernel")
}

func TestRun(t *testing.T) {
	dir := t.TempDir()
	old, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(old)

	mkfile(t, ".", "sources/xcode/Application/Application/Plugins.swift", "stock plugins")
	mkfile(t, ".", "build/xcode/sources/Application/Application/Plugins.swift", "generated by plugins tool")
	mkfile(t, ".", "build/xcode/config/config.jsonc", "cfg")
	mkfile(t, ".", "lib/xcode/sources/Application/Application/Plugins.swift", "lib override")

	if err := run([]string{"--only", "xcode"}); err != nil {
		t.Fatal(err)
	}

	assertFile(t, filepath.Join("build", "xcode", "sources"), "Application/Application/Plugins.swift", "lib override")
	assertFile(t, filepath.Join("build", "xcode"), "config/config.jsonc", "cfg")
}

func mkfile(t *testing.T, base, rel, content string) {
	t.Helper()
	path := filepath.Join(base, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func assertFile(t *testing.T, base, rel, want string) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(base, rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	if string(data) != want {
		t.Errorf("%s = %q, want %q", rel, data, want)
	}
}
